name: Daily LLM Stats Summary (Live only)

on:
  schedule:
    - cron: "0 6 * * *"  # 06:00 UTC = 09:00 Asia/Riyadh
  workflow_dispatch: {}

permissions:
  contents: write  # allow committing snapshot

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests playwright
          python -m playwright install --with-deps chromium

      - name: Run summarizer (live)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COMMIT_CHANGES: "1"
        run: python summarize_llm_stats.py
